### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by scampiuk** [contentstack/contentstack-express#2]
**Is your feature request related to a problem? Please describe.**
We can't clearly see what has changed between one version and another

**Describe the solution you'd like**
A change log, describing the differences and impacts of changes per tagged version

**Describe alternatives you've considered**
Reading through the commits, there doesn't appear to be Pull Requests....

**Additional context**
None

**Comment by iyerrama29** [comment]
Hi @scampiuk , 

Thank you for letting us know, we will take this under consideration.

For time being please refer to our release notes to track the changes between versions.

**Comment by iyerrama29** [comment]
@scampiuk : This issue has been discussed internally.

We'll be keeping a list of updated 'release notes' which can be referred for noting changes from one module to another.

In future versions, if need arises we'll be sure to add a 'changelog'.

Thanks for sharing, please do let us know if you have any further questions/suggestions!

Regards,
Ramanathan K
